# Core WebRTC Relay Settings
listening-port=3478
tls-listening-port=53478
alt-listening-port=0

# Security requirements 
lt-cred-mech
fingerprint

# Enforce secure DTLS/TLS ciphers to maintain Forward Secrecy
ssl-crypto-ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256

# Dynamic media relay port allocation range
min-port=49152
max-port=65535

# Set up a static user credential for team's testing
user=sharebyteam:SecurePass2026

# Bind server public EC2 IP address
external-ip=13.207.1.49
realm=traversal.org